from pptx import Presentation
import os

def generate_ppt_file(title: str, slides_data: list, output_path: str):
    """
    slides_data format:
    [
        {"title": "Introduction", "points": ["Point 1", "Point 2"]},
        {"title": "Conclusion", "points": ["Summary", "Next steps"]}
    ]
    """
    prs = Presentation()
    
    # Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title_shape = slide.shapes.title
    subtitle = slide.placeholders[1]
    
    title_shape.text = title
    subtitle.text = "Generated by Unified AI Service"
    
    # Content Slides
    bullet_slide_layout = prs.slide_layouts[1]
    
    for slide_data in slides_data:
        slide = prs.slides.add_slide(bullet_slide_layout)
        shapes = slide.shapes
        
        slide_title = shapes.title
        body_shape = shapes.placeholders[1]
        
        slide_title.text = slide_data.get("title", "Slide Title")
        
        tf = body_shape.text_frame
        points = slide_data.get("points", [])
        
        if points:
            tf.text = points[0] # First point
            for point in points[1:]:
                p = tf.add_paragraph()
                p.text = point

    prs.save(output_path)
    return output_path
